services:
  backend:
    build: ./story-collab-backend
    image: mern-backend:v1
    ports:
      - "5000:5000" 
    networks:
      - mern_network 
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: mern-frontend:v1
    ports:
      - "3000:3000"  
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5000 

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally
